export type {
  SupportTicketPriority,
  SupportTicketStatus,
  SupportCommunicationChannel,
  SupportPortal,
  SupportTicketAttachment,
  SupportCustomerMessage,
  SupportSystemEvent,
  SupportConversationEntry,
  SupportTicketDraft,
  SupportTicketCustomerContext,
  SupportTicket,
  SupportTicketListFilters,
  SupportTicketListingAggregates,
  SupportTicketReplyInput,
} from '@/shared/types/supportTicket'
