import { Box, Divider, Stack, Typography } from '@mui/material'
import { Button } from '@/design-system/UIComponents'
import { formatInr } from '@/shared/utils/invoiceCalculations'
import type { GroundOpsClaimSheet } from '@/shared/types/groundOpsClaimSheet'
import {
  CLAIM_SHEET_STATUS_LABEL,
  getClaimSheetFundTransferLabel,
} from '@/shared/types/groundOpsClaimSheet'
import { ClaimSheetKpiSnapshot } from './ClaimSheetKpiSnapshot'

interface ClaimSheetDetailBodyProps {
  sheet: GroundOpsClaimSheet
  onDownloadPdf?: () => void
  onDownloadProofs?: () => void
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <Stack spacing={0.25} minWidth={0}>
      <Typography variant="caption" color="text.secondary" fontWeight={600} sx={{ fontSize: 11 }}>
        {label}
      </Typography>
      <Typography variant="body2" sx={{ fontSize: 13, fontWeight: 500 }}>
        {value || '—'}
      </Typography>
    </Stack>
  )
}

export function ClaimSheetDetailBody({
  sheet,
  onDownloadPdf,
  onDownloadProofs,
}: ClaimSheetDetailBodyProps) {
  return (
    <Stack spacing={2}>
      <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
        {onDownloadPdf ? (
          <Button label="Download PDF" variant="contained" size="sm" onClick={onDownloadPdf} />
        ) : null}
        {onDownloadProofs ? (
          <Button
            label="Download proofs"
            variant="neutral"
            size="sm"
            onClick={onDownloadProofs}
            disabled={sheet.proofDocuments.length === 0}
          />
        ) : null}
      </Stack>

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
          gap: 1.25,
          p: 1.5,
          borderRadius: 1.5,
          border: 1,
          borderColor: 'divider',
          bgcolor: 'action.hover',
        }}
      >
        <Meta label="Claim number" value={sheet.claimNumber} />
        <Meta label="Status" value={CLAIM_SHEET_STATUS_LABEL[sheet.status]} />
        <Meta label="Generated by" value={sheet.generatedBy} />
        <Meta
          label="Generated at"
          value={new Date(sheet.generatedAt).toLocaleString('en-GB', {
            day: '2-digit',
            month: 'short',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
          })}
        />
        <Meta label="Team" value={sheet.team} />
        <Meta label="Transfer type" value={getClaimSheetFundTransferLabel(sheet.fundTransferType)} />
        <Meta label="Grand total" value={formatInr(sheet.grandTotal)} />
        {sheet.reviewedBy ? <Meta label="Reviewed by" value={sheet.reviewedBy} /> : null}
        {sheet.reviewedAt ? (
          <Meta
            label="Reviewed at"
            value={new Date(sheet.reviewedAt).toLocaleString('en-GB', {
              day: '2-digit',
              month: 'short',
              year: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
            })}
          />
        ) : null}
        {sheet.rejectionReason ? <Meta label="Rejection reason" value={sheet.rejectionReason} /> : null}
      </Box>

      <ClaimSheetKpiSnapshot kpis={sheet.kpis} fundTransferType={sheet.fundTransferType} />

      <Divider />

      <Stack spacing={1.25}>
        <Typography variant="body2" fontWeight={600} sx={{ fontSize: 12 }}>
          Selected cases & services
        </Typography>
        {sheet.cases.map(caseRow => (
          <Box
            key={caseRow.caseId}
            sx={{
              p: 1.25,
              borderRadius: 1.25,
              border: 1,
              borderColor: 'divider',
              bgcolor: 'background.paper',
            }}
          >
            <Typography variant="body2" fontWeight={700} sx={{ fontSize: 13 }}>
              {caseRow.passengerName} · {caseRow.operationalId}
            </Typography>
            <Typography variant="caption" color="text.secondary" sx={{ fontSize: 11 }}>
              {caseRow.applicationId} · {caseRow.country} · {caseRow.visaType}
            </Typography>

            <Stack spacing={0.5} sx={{ mt: 1 }}>
              {caseRow.services.map((service, index) => (
                <Stack
                  key={`${caseRow.caseId}-svc-${index}`}
                  direction="row"
                  justifyContent="space-between"
                  spacing={1}
                >
                  <Typography variant="body2" sx={{ fontSize: 12 }}>
                    {service.serviceName}
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: 12, fontWeight: 600 }}>
                    {formatInr(service.amount)}
                  </Typography>
                </Stack>
              ))}
              {caseRow.additionalExpenses.map((expense, index) => (
                <Stack
                  key={`${caseRow.caseId}-exp-${index}`}
                  direction="row"
                  justifyContent="space-between"
                  spacing={1}
                >
                  <Typography variant="body2" sx={{ fontSize: 12 }}>
                    {expense.serviceName} (additional)
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: 12, fontWeight: 600 }}>
                    {formatInr(expense.amount)}
                  </Typography>
                </Stack>
              ))}
              {caseRow.dispatchCharge > 0 ? (
                <Stack direction="row" justifyContent="space-between" spacing={1}>
                  <Typography variant="body2" sx={{ fontSize: 12 }}>
                    Dispatch charges
                  </Typography>
                  <Typography variant="body2" sx={{ fontSize: 12, fontWeight: 600 }}>
                    {formatInr(caseRow.dispatchCharge)}
                  </Typography>
                </Stack>
              ) : null}
              <Stack direction="row" justifyContent="space-between" spacing={1} sx={{ pt: 0.5 }}>
                <Typography variant="body2" fontWeight={700} sx={{ fontSize: 12 }}>
                  Case total
                </Typography>
                <Typography variant="body2" fontWeight={700} sx={{ fontSize: 12 }}>
                  {formatInr(caseRow.caseExpenseTotal)}
                </Typography>
              </Stack>
            </Stack>
          </Box>
        ))}
      </Stack>

      {sheet.otherExpenses.length > 0 ? (
        <Stack spacing={1}>
          <Typography variant="body2" fontWeight={600} sx={{ fontSize: 12 }}>
            Other expenses
          </Typography>
          {sheet.otherExpenses.map(expense => (
            <Stack key={expense.id} direction="row" justifyContent="space-between" spacing={1}>
              <Typography variant="body2" sx={{ fontSize: 12 }}>
                {expense.description}
              </Typography>
              <Typography variant="body2" sx={{ fontSize: 12, fontWeight: 600 }}>
                {formatInr(expense.amount)}
              </Typography>
            </Stack>
          ))}
          <Stack direction="row" justifyContent="space-between">
            <Typography variant="body2" fontWeight={700} sx={{ fontSize: 12 }}>
              Other expenses total
            </Typography>
            <Typography variant="body2" fontWeight={700} sx={{ fontSize: 12 }}>
              {formatInr(sheet.otherExpensesTotal)}
            </Typography>
          </Stack>
        </Stack>
      ) : null}

      {sheet.proofDocuments.length > 0 ? (
        <Stack spacing={0.75}>
          <Typography variant="body2" fontWeight={600} sx={{ fontSize: 12 }}>
            Proof documents ({sheet.proofDocuments.length})
          </Typography>
          {sheet.proofDocuments.map(doc => (
            <Typography key={doc.id} variant="caption" color="text.secondary" sx={{ fontSize: 11 }}>
              {doc.label}: {doc.fileName}
            </Typography>
          ))}
        </Stack>
      ) : null}

      {sheet.notes.trim() ? (
        <Meta label="Notes" value={sheet.notes} />
      ) : null}
    </Stack>
  )
}
