import { useMemo, useState } from 'react'
import { Box, Stack, Typography } from '@mui/material'
import { Button, Drawer, EmptyState, useToast } from '@/design-system/UIComponents'
import { groundOpsClaimSheetService } from '@/shared/services/groundOpsClaimSheetService'
import { formatInr } from '@/shared/utils/invoiceCalculations'
import type { GroundOpsClaimSheet } from '@/shared/types/groundOpsClaimSheet'
import { CLAIM_SHEET_STATUS_LABEL } from '@/shared/types/groundOpsClaimSheet'
import { ClaimSheetDetailBody } from './ClaimSheetDetailBody'

const DRAWER_WIDTH = 640

interface ClaimSheetListDrawerProps {
  open: boolean
  refreshKey?: number
  onClose: () => void
}

export function ClaimSheetListDrawer({ open, refreshKey = 0, onClose }: ClaimSheetListDrawerProps) {
  const { showToast } = useToast()
  const [selectedId, setSelectedId] = useState<string | null>(null)

  const sheets = useMemo(() => {
    void refreshKey
    void open
    return groundOpsClaimSheetService.list()
  }, [open, refreshKey])

  const selected = selectedId ? groundOpsClaimSheetService.getById(selectedId) : null

  const handleClose = () => {
    setSelectedId(null)
    onClose()
  }

  return (
    <Drawer
      open={open}
      onClose={handleClose}
      title={selected ? selected.claimNumber : 'Claim sheets'}
      subtitle={
        selected
          ? `Generated by ${selected.generatedBy}`
          : 'Submitted claim sheets for future reference'
      }
      width={DRAWER_WIDTH}
      footer={
        <Stack direction="row" justifyContent="space-between" spacing={1}>
          {selected ? (
            <Button label="Back to list" variant="neutral" onClick={() => setSelectedId(null)} />
          ) : (
            <Box />
          )}
          <Button label="Close" variant="contained" onClick={handleClose} />
        </Stack>
      }
      bodyVariant="default"
    >
      {selected ? (
        <ClaimSheetDetailBody
          sheet={selected}
          onDownloadPdf={() =>
            showToast({
              title: 'PDF download started',
              description: groundOpsClaimSheetService.getPdfDownloadLabel(selected),
              variant: 'success',
            })
          }
          onDownloadProofs={() =>
            showToast({
              title: 'Proofs download started',
              description: groundOpsClaimSheetService.getProofsDownloadLabel(selected),
              variant: 'success',
            })
          }
        />
      ) : sheets.length === 0 ? (
        <EmptyState
          title="No claim sheets yet"
          description="Generate a claim sheet from completed cases to see it here."
        />
      ) : (
        <Stack spacing={1}>
          {sheets.map(sheet => (
            <ClaimSheetListRow key={sheet.id} sheet={sheet} onOpen={() => setSelectedId(sheet.id)} />
          ))}
        </Stack>
      )}
    </Drawer>
  )
}

function ClaimSheetListRow({
  sheet,
  onOpen,
}: {
  sheet: GroundOpsClaimSheet
  onOpen: () => void
}) {
  return (
    <Box
      onClick={onOpen}
      sx={{
        p: 1.25,
        borderRadius: 1.25,
        border: 1,
        borderColor: 'divider',
        bgcolor: 'background.paper',
        cursor: 'pointer',
        '&:hover': { borderColor: 'primary.main' },
      }}
    >
      <Stack direction="row" justifyContent="space-between" spacing={1} alignItems="flex-start">
        <Box minWidth={0}>
          <Typography variant="body2" fontWeight={700} sx={{ fontSize: 13 }}>
            {sheet.claimNumber}
          </Typography>
          <Typography variant="caption" color="text.secondary" sx={{ fontSize: 11 }}>
            {sheet.generatedBy} · {CLAIM_SHEET_STATUS_LABEL[sheet.status]} · {sheet.cases.length}{' '}
            case(s)
          </Typography>
        </Box>
        <Typography variant="body2" fontWeight={700} sx={{ fontSize: 13, flexShrink: 0 }}>
          {formatInr(sheet.grandTotal)}
        </Typography>
      </Stack>
    </Box>
  )
}
