import { useMemo, useState } from 'react'
import { Box, Stack } from '@mui/material'
import { Badge, RowActions, Tabs, useToast, type Column } from '@/design-system/UIComponents'
import { AccountsWorkListing } from '../components/AccountsWorkListing'
import type {
  AccountsClaimSheetRow,
  AccountsDashboardTabProps,
  AccountsFundAllocationRow,
} from '../types'

type FundDeskTab = 'pending' | 'allocated' | 'claim_sheets'

function statusColor(status: string): 'success' | 'warning' | 'error' | 'info' | 'neutral' {
  const s = status.toLowerCase()
  if (s.includes('allocat') && !s.includes('pending')) return 'success'
  if (s.includes('approved')) return 'success'
  if (s.includes('pending')) return 'warning'
  if (s.includes('reject')) return 'error'
  return 'info'
}

function getFundCell(row: AccountsFundAllocationRow, key: string): string {
  const value = row[key as keyof AccountsFundAllocationRow]
  return value == null ? '' : String(value)
}

function getClaimCell(row: AccountsClaimSheetRow, key: string): string {
  const value = row[key as keyof AccountsClaimSheetRow]
  return value == null ? '' : String(value)
}

/** Fund allocation desk — Ops requests + Ground Ops claim sheets. */
export function FundAllocationDeskTab({
  data,
  loading,
  onNavigate,
}: AccountsDashboardTabProps) {
  const { showToast } = useToast()
  const [deskTab, setDeskTab] = useState<FundDeskTab>('pending')

  const pending = data.fundAllocationRows.filter((r) => r.allocationStatus === 'Pending')
  const allocated = data.fundAllocationRows.filter((r) => r.allocationStatus === 'Allocated')
  const claimPending = data.claimSheetRows.filter((r) => r.status === 'Pending review')

  const fundColumns: Column<AccountsFundAllocationRow>[] = useMemo(
    () => [
      {
        key: 'applicant',
        label: 'Passenger',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'segment',
        label: 'Customer type',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
      },
      {
        key: 'glNumber',
        label: 'Application',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'country',
        label: 'Jurisdiction',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'company',
        label: 'Company Name',
        widthSize: 'lg',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'requestedBy',
        label: 'User',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'visaType',
        label: 'Visa Type',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'amount',
        label: deskTab === 'allocated' ? 'Allocated fund value' : 'Requested total',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'allocationStatus',
        label: 'Status',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
        render: (_value, row) => (
          <Badge label={row.allocationStatus} color={statusColor(row.allocationStatus)} />
        ),
      },
      {
        key: 'actions',
        label: '',
        hideable: false,
        sortable: false,
        filterable: false,
        searchable: false,
        width: 56,
        render: (_value, row) => (
          <RowActions
            actions={[
              {
                label: row.allocationStatus === 'Pending' ? 'Allocate funds' : 'View details',
                onClick: () =>
                  onNavigate(
                    `/admin/finance/fund-allocation?tab=${
                      row.allocationStatus === 'Pending' ? 'pending_allocation' : 'allocated'
                    }`,
                  ),
              },
            ]}
          />
        ),
      },
    ],
    [deskTab, onNavigate],
  )

  const claimColumns: Column<AccountsClaimSheetRow>[] = useMemo(
    () => [
      {
        key: 'claimSheetNo',
        label: 'Claim number',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'groundOpsUser',
        label: 'Generated by',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'branch',
        label: 'Team',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'casesCount',
        label: 'Cases',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
      },
      {
        key: 'amount',
        label: 'Allocated amount',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'submittedDate',
        label: 'Generated at',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'status',
        label: 'Status',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
        render: (_value, row) => <Badge label={row.status} color={statusColor(row.status)} />,
      },
      {
        key: 'actions',
        label: '',
        hideable: false,
        sortable: false,
        filterable: false,
        searchable: false,
        width: 56,
        render: (_value, row) => (
          <RowActions
            actions={[
              {
                label: 'View details',
                onClick: () => onNavigate('/admin/finance/fund-allocation?tab=claim_sheets'),
              },
              ...(row.status === 'Pending review'
                ? [
                    {
                      label: 'Approve',
                      onClick: () =>
                        showToast({
                          title: 'Claim sheet approved',
                          description: `${row.claimSheetNo} marked approved (mock).`,
                          variant: 'success',
                        }),
                    },
                    {
                      label: 'Reject',
                      onClick: () =>
                        showToast({
                          title: 'Claim sheet rejected',
                          description: `${row.claimSheetNo} marked rejected (mock).`,
                          variant: 'warning',
                        }),
                    },
                  ]
                : []),
            ]}
          />
        ),
      },
    ],
    [onNavigate, showToast],
  )

  return (
    <Stack spacing={1.5}>
      <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Tabs
          value={deskTab}
          onChange={(value) => setDeskTab(value as FundDeskTab)}
          variant="underline"
          size="sm"
          items={[
            { value: 'pending', label: `Pending (${pending.length})` },
            { value: 'allocated', label: `Allocated (${allocated.length})` },
            { value: 'claim_sheets', label: `Claim sheets (${claimPending.length})` },
          ]}
        />
      </Box>

      {deskTab === 'pending' ? (
        <AccountsWorkListing
          title="Pending fund allocation"
          description="Unallocated Ops requests"
          rows={pending}
          columns={fundColumns}
          getCellValue={getFundCell}
          loading={loading}
          onOpen={() => onNavigate('/admin/finance/fund-allocation?tab=pending_allocation')}
          onViewAll={() => onNavigate('/admin/finance/fund-allocation?tab=pending_allocation')}
          viewAllLabel="Open fund allocation"
          searchPlaceholder="Search request, applicant, country…"
          exportFileName="fund-pending"
          emptyTitle="No pending allocations"
          emptyDescription="Ops fund requests will appear here."
        />
      ) : null}

      {deskTab === 'allocated' ? (
        <AccountsWorkListing
          title="Allocated funds"
          description="Recently allocated requests"
          rows={allocated}
          columns={fundColumns}
          getCellValue={getFundCell}
          loading={loading}
          onOpen={() => onNavigate('/admin/finance/fund-allocation?tab=allocated')}
          onViewAll={() => onNavigate('/admin/finance/fund-allocation?tab=allocated')}
          viewAllLabel="Open allocated"
          searchPlaceholder="Search request, applicant, country…"
          exportFileName="fund-allocated"
          emptyTitle="No allocated rows"
          emptyDescription="Completed allocations will appear here."
        />
      ) : null}

      {deskTab === 'claim_sheets' ? (
        <AccountsWorkListing
          title="Claim sheets"
          description="Ground Ops claim sheets — approve or reject"
          rows={data.claimSheetRows}
          columns={claimColumns}
          getCellValue={getClaimCell}
          loading={loading}
          onOpen={() => onNavigate('/admin/finance/fund-allocation?tab=claim_sheets')}
          onViewAll={() => onNavigate('/admin/finance/fund-allocation?tab=claim_sheets')}
          viewAllLabel="Open claim sheets"
          searchPlaceholder="Search sheet, applicant, status…"
          exportFileName="claim-sheets"
          emptyTitle="No claim sheets"
          emptyDescription="Ground Ops claim sheets will appear here for finance review."
        />
      ) : null}
    </Stack>
  )
}
