import { useMemo, useState } from 'react'
import { Box, Stack } from '@mui/material'
import { Badge, RowActions, Tabs, type Column } from '@/design-system/UIComponents'
import { AccountsWorkListing } from '../components/AccountsWorkListing'
import type {
  AccountsClaimSheetRow,
  AccountsDashboardTabProps,
  AccountsReconciliationRow,
} from '../types'
import {
  countReconciliationDeskRows,
  filterPendingReconciliationRows,
  reconciliationModuleTabHref,
  type ReconciliationDeskTabId,
} from '../utils/accountsReconciliationDeskUtils'

function statusColor(status: string): 'success' | 'warning' | 'error' | 'info' | 'neutral' {
  const normalized = status.toLowerCase()
  if (normalized.includes('match') || normalized.includes('approved')) return 'success'
  if (normalized.includes('review') || normalized.includes('pending') || normalized.includes('due')) {
    return 'warning'
  }
  if (normalized.includes('partial')) return 'error'
  return 'info'
}

function getReconCell(row: AccountsReconciliationRow, key: string): string {
  const value = row[key as keyof AccountsReconciliationRow]
  return value == null ? '' : String(value)
}

function getClaimCell(row: AccountsClaimSheetRow, key: string): string {
  const value = row[key as keyof AccountsClaimSheetRow]
  return value == null ? '' : String(value)
}

/** Reconciliation desk — insurance · tickets · couriers · cards · claim sheets. */
export function ReconciliationDeskTab({
  data,
  loading,
  onNavigate,
}: AccountsDashboardTabProps) {
  const [deskTab, setDeskTab] = useState<ReconciliationDeskTabId>('insurance')

  const insuranceRows = useMemo(
    () => filterPendingReconciliationRows(data.reconciliationRows, 'insurance'),
    [data.reconciliationRows],
  )
  const ticketRows = useMemo(
    () => filterPendingReconciliationRows(data.reconciliationRows, 'ticket'),
    [data.reconciliationRows],
  )
  const courierRows = useMemo(
    () => filterPendingReconciliationRows(data.reconciliationRows, 'courier'),
    [data.reconciliationRows],
  )
  const cardRows = useMemo(
    () => filterPendingReconciliationRows(data.reconciliationRows, 'cards'),
    [data.reconciliationRows],
  )
  const claimRows = useMemo(
    () => data.claimSheetRows.filter((row) => row.status === 'Approved'),
    [data.claimSheetRows],
  )

  const reconColumns: Column<AccountsReconciliationRow>[] = useMemo(
    () => [
      {
        key: 'reference',
        label: 'Reference',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'category',
        label: 'Pack',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'vendor',
        label: 'Vendor',
        widthSize: 'lg',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'amount',
        label: 'Amount',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'dueDate',
        label: 'Due',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
      },
      {
        key: 'assignedTo',
        label: 'Assigned',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'status',
        label: 'Status',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
        render: (_value, row) => <Badge label={row.status} color={statusColor(row.status)} />,
      },
      {
        key: 'actions',
        label: '',
        hideable: false,
        sortable: false,
        filterable: false,
        searchable: false,
        width: 56,
        render: (_value, _row) => (
          <RowActions
            actions={[
              {
                label: 'Open reconciliation',
                onClick: () => onNavigate(reconciliationModuleTabHref(deskTab)),
              },
              {
                label: 'View reference',
                onClick: () => onNavigate(reconciliationModuleTabHref(deskTab)),
              },
            ]}
          />
        ),
      },
    ],
    [deskTab, onNavigate],
  )

  const claimColumns: Column<AccountsClaimSheetRow>[] = useMemo(
    () => [
      {
        key: 'claimSheetNo',
        label: 'Claim sheet',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'groundOpsUser',
        label: 'Generated by',
        widthSize: 'md',
        sortable: true,
        filterable: true,
        searchable: true,
      },
      {
        key: 'casesCount',
        label: 'Cases',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
      },
      {
        key: 'amount',
        label: 'Amount',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'submittedDate',
        label: 'Approved',
        widthSize: 'md',
        sortable: true,
        filterable: true,
      },
      {
        key: 'status',
        label: 'Status',
        widthSize: 'sm',
        sortable: true,
        filterable: true,
        render: (_value, row) => <Badge label={row.status} color={statusColor(row.status)} />,
      },
      {
        key: 'actions',
        label: '',
        hideable: false,
        sortable: false,
        filterable: false,
        searchable: false,
        width: 56,
        render: () => (
          <RowActions
            actions={[
              {
                label: 'Open claim reconciliation',
                onClick: () => onNavigate(reconciliationModuleTabHref('claim_sheets')),
              },
            ]}
          />
        ),
      },
    ],
    [onNavigate],
  )

  const activeReconRows =
    deskTab === 'insurance'
      ? insuranceRows
      : deskTab === 'ticket'
        ? ticketRows
        : deskTab === 'courier'
          ? courierRows
          : cardRows

  const tabItems = useMemo(
    () => [
      { value: 'insurance' as const, label: `Insurance (${countReconciliationDeskRows(data, 'insurance')})` },
      { value: 'ticket' as const, label: `Ticket (${countReconciliationDeskRows(data, 'ticket')})` },
      { value: 'courier' as const, label: `Courier (${countReconciliationDeskRows(data, 'courier')})` },
      { value: 'cards' as const, label: `Credit card (${countReconciliationDeskRows(data, 'cards')})` },
      {
        value: 'claim_sheets' as const,
        label: `Claim sheets (${countReconciliationDeskRows(data, 'claim_sheets')})`,
      },
    ],
    [data],
  )

  return (
    <Stack spacing={1.5}>
      <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Tabs
          value={deskTab}
          onChange={(value) => setDeskTab(value as ReconciliationDeskTabId)}
          variant="underline"
          size="sm"
          items={tabItems}
        />
      </Box>

      {deskTab === 'claim_sheets' ? (
        <AccountsWorkListing
          title="Approved claim sheets"
          description="Ground Ops claim sheets awaiting book entry reconciliation"
          rows={claimRows}
          columns={claimColumns}
          getCellValue={getClaimCell}
          loading={loading}
          onOpen={() => onNavigate(reconciliationModuleTabHref('claim_sheets'))}
          onViewAll={() => onNavigate(reconciliationModuleTabHref('claim_sheets'))}
          viewAllLabel="Open reconciliation"
          searchPlaceholder="Search claim sheet, team, branch…"
          exportFileName="claim-sheet-reconciliation"
          emptyTitle="No claim sheets to reconcile"
          emptyDescription="Approved claim sheets will appear here for finance reconciliation."
        />
      ) : (
        <AccountsWorkListing
          title="Pending reconciliation"
          description="Insurance · tickets · couriers · credit cards"
          rows={activeReconRows}
          columns={reconColumns}
          getCellValue={getReconCell}
          loading={loading}
          onOpen={() => onNavigate(reconciliationModuleTabHref(deskTab))}
          onViewAll={() => onNavigate(reconciliationModuleTabHref(deskTab))}
          viewAllLabel="Open reconciliation"
          searchPlaceholder="Search reference, vendor, category…"
          exportFileName={`reconciliation-${deskTab}`}
          emptyTitle="No pending reconciliation"
          emptyDescription="Matched packs will drop off this desk queue."
        />
      )}
    </Stack>
  )
}
