import { Typography } from '@mui/material'
import { Eye } from 'lucide-react'
import { Badge, RowActions, type Column, type RowAction } from '@/design-system/UIComponents'
import { adminListingColumnWidthSize } from '@/pages/admin/components/listing'
import type { ReconciliationClaimSheetRow } from '@/shared/types/reconciliation'
import {
  CLAIM_SHEET_STATUS_LABEL,
  getClaimSheetFundTransferLabel,
  getClaimSheetStatusBadgeColor,
  isClaimSheetBankTransferKpis,
} from '@/shared/types/groundOpsClaimSheet'
import { formatDisplayDateTime } from '@/shared/utils/formatDisplayDate'
import { formatInr } from '@/shared/utils/invoiceCalculations'
import {
  formatSettlementAmountLabel,
  getSettlementAmountColor,
  getSettlementAmountTone,
} from '@/shared/utils/fundSettlementDisplay'
import {
  getReconciliationStatusBadgeColor,
  getReconciliationStatusLabel,
} from '../config/reconciliationListingConfig'

export type ReconciliationClaimSheetAction = 'view' | 'reconcile'

export interface ReconciliationClaimSheetTableColumnsParams {
  onAction: (action: ReconciliationClaimSheetAction, row: ReconciliationClaimSheetRow) => void
}

function AmountCell({
  value,
  emphasize = false,
  color,
}: {
  value: string
  emphasize?: boolean
  color?: string
}) {
  return (
    <Typography
      variant="body2"
      color={color}
      sx={{ fontSize: 13, fontWeight: emphasize ? 600 : 500 }}
      noWrap
    >
      {value}
    </Typography>
  )
}

export function buildReconciliationClaimSheetTableColumns(
  params: ReconciliationClaimSheetTableColumnsParams,
): Column<ReconciliationClaimSheetRow>[] {
  return [
    {
      key: 'claimNumber',
      label: 'Claim number',
      widthSize: adminListingColumnWidthSize('name'),
      sortable: true,
      searchable: true,
      hideable: false,
      render: (_value, row) => (
        <Typography variant="body2" fontWeight={600} noWrap sx={{ fontSize: 13 }}>
          {row.sheet.claimNumber}
        </Typography>
      ),
    },
    {
      key: 'fundTransferType',
      label: 'Transfer type',
      widthSize: adminListingColumnWidthSize('status'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {getClaimSheetFundTransferLabel(row.sheet.fundTransferType)}
        </Typography>
      ),
    },
    {
      key: 'generatedBy',
      label: 'Generated by',
      widthSize: adminListingColumnWidthSize('name'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {row.sheet.generatedBy || '—'}
        </Typography>
      ),
    },
    {
      key: 'team',
      label: 'Team',
      widthSize: adminListingColumnWidthSize('status'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {row.sheet.team || '—'}
        </Typography>
      ),
    },
    {
      key: 'claimSheetStatus',
      label: 'Claim status',
      widthSize: 'md',
      sortable: true,
      render: (_value, row) => (
        <Badge
          label={CLAIM_SHEET_STATUS_LABEL[row.sheet.status]}
          color={getClaimSheetStatusBadgeColor(row.sheet.status)}
        />
      ),
    },
    {
      key: 'caseCount',
      label: 'Cases',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => (
        <Typography variant="body2" sx={{ fontSize: 13 }}>
          {row.sheet.cases.length}
        </Typography>
      ),
    },
    {
      key: 'allocatedAmount',
      label: 'Allocated amount',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => <AmountCell value={formatInr(row.sheet.kpis.allocatedAmount)} />,
    },
    {
      key: 'expensesIncurred',
      label: 'Expenses incurred',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => <AmountCell value={formatInr(row.sheet.kpis.expensesIncurred)} />,
    },
    {
      key: 'settlementAmount',
      label: 'Settlement amount',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => {
        const convention = isClaimSheetBankTransferKpis(row.sheet.fundTransferType)
          ? 'closing_cash'
          : 'expense_vs_allocated'
        return (
          <AmountCell
            value={formatSettlementAmountLabel(row.sheet.kpis.settlementAmount, convention)}
            color={getSettlementAmountColor(
              getSettlementAmountTone(row.sheet.kpis.settlementAmount, convention),
            )}
            emphasize
          />
        )
      },
    },
    {
      key: 'generatedAt',
      label: 'Generated at',
      widthSize: adminListingColumnWidthSize('date'),
      sortable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {formatDisplayDateTime(row.sheet.generatedAt)}
        </Typography>
      ),
    },
    {
      key: 'reconciliationStatus',
      label: 'Reconciliation',
      widthSize: adminListingColumnWidthSize('status'),
      sortable: true,
      render: (_value, row) => (
        <Badge
          label={getReconciliationStatusLabel(row.status)}
          color={getReconciliationStatusBadgeColor(row.status)}
          size="sm"
        />
      ),
    },
    {
      key: 'reconciledBy',
      label: 'User',
      widthSize: adminListingColumnWidthSize('name'),
      sortable: true,
      searchable: true,
      render: (_value, row) => row.reconciledBy || '—',
    },
    {
      key: 'actions',
      label: '',
      hideable: false,
      sortable: false,
      filterable: false,
      searchable: false,
      render: (_value, row) => {
        const actions: RowAction[] = [
          {
            label: row.status === 'pending' ? 'Reconcile' : 'View',
            icon: row.status === 'pending' ? undefined : <Eye size={16} />,
            onClick: () =>
              params.onAction(row.status === 'pending' ? 'reconcile' : 'view', row),
          },
        ]
        return <RowActions row={row} actions={actions} />
      },
    },
  ]
}
