import { useCallback, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useToast } from '@/design-system/UIComponents'
import { CustomerListingShell } from '@/pages/customer/features/shared/components/listing/CustomerListingShell'
import { CustomerListingToolbar } from '@/pages/customer/features/shared/components/listing/CustomerListingToolbar'
import { CustomerListingTable } from '@/pages/customer/features/shared/components/listing/CustomerListingTable'
import { CustomerListingPagination } from '@/pages/customer/features/shared/components/listing/CustomerListingPagination'
import { useCustomerListing } from '@/pages/customer/features/shared/hooks/useCustomerListing'
import { useCustomerPortalBase } from '@/pages/customer/features/shared/hooks/useCustomerPortalBase'
import { customerFinanceService } from '@/shared/services/customerFinanceService'
import { buildInvoiceListingColumns } from '../components/invoices/invoiceListingColumns'
import {
  getInvoiceListingCellValue,
  invoiceListingSearchMatch,
} from '../utils/financeListingUtils'
import type { InvoiceListingRow } from '../types/customerFinance.types'
import type { Column } from '@/design-system/UIComponents'

export function InvoiceListingPage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const applicationFilter = searchParams.get('applicationId')
  const { base, isSuperAdmin } = useCustomerPortalBase()
  const { showToast } = useToast()
  const [viewMode, setViewMode] = useState<'table' | 'grid'>('table')

  const allRows = useMemo(() => customerFinanceService.getInvoiceListingRows(), [])
  const rows = useMemo(() => {
    if (!applicationFilter) return allRows
    return allRows.filter(r =>
      customerFinanceService.getInvoicesForApplication(applicationFilter).some(i => i.id === r.invoice.id),
    )
  }, [allRows, applicationFilter])

  const listing = useCustomerListing({
    rows,
    getCellValue: getInvoiceListingCellValue,
    searchMatch: invoiceListingSearchMatch,
  })

  const columnParams = useMemo(
    () => ({ base, navigate, showToast }),
    [base, navigate, showToast],
  )

  const columns = useMemo(
    () => buildInvoiceListingColumns(columnParams) as Column<InvoiceListingRow>[],
    [columnParams],
  )

  const toolbarColumns = useMemo(
    () => columns.filter(c => c.key !== 'actions').map(c => ({ key: c.key, label: c.label })),
    [columns],
  )

  const handleExport = useCallback(() => {
    if (!isSuperAdmin) {
      showToast({ title: 'Export not available', description: 'Only Super Admin can export.', variant: 'warning' })
      return
    }
    const csv = customerFinanceService.exportFinanceData()
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'invoices-export.csv'
    a.click()
    URL.revokeObjectURL(url)
    showToast({ title: 'Export complete', variant: 'success' })
  }, [isSuperAdmin, showToast])

  const handleRowClick = useCallback(
    (row: InvoiceListingRow) => navigate(`${base}/finance/invoices/${row.invoice.id}`),
    [base, navigate],
  )

  return (
    <CustomerListingShell
      title="Invoice Management"
      subtitle={
        applicationFilter
          ? `Invoices linked to ${applicationFilter}`
          : 'Invoices generated by the GLTS Accounts Team and shared with your company.'
      }
      toolbar={
        <CustomerListingToolbar
          searchValue={listing.tableState.searchQuery}
          onSearch={listing.handleSearch}
          searchPlaceholder="Search invoices…"
          onExport={isSuperAdmin ? handleExport : undefined}
          viewMode={viewMode}
          onViewModeChange={setViewMode}
          columns={toolbarColumns}
          hiddenColumnKeys={listing.tableState.hiddenColumnKeys}
          onHiddenColumnKeysChange={keys => listing.setTableState(s => ({ ...s, hiddenColumnKeys: keys }))}
        />
      }
      table={
        <CustomerListingTable<InvoiceListingRow>
          columns={columns}
          data={listing.paginatedRows}
          filterSourceData={listing.filterSourceRows}
          rowKey="id"
          state={listing.tableState}
          onStateChange={listing.setTableState}
          columnFilters={listing.columnFilters}
          onColumnFiltersChange={listing.setColumnFilters}
          getCellValue={getInvoiceListingCellValue}
          onRowClick={handleRowClick}
          stickyHeader
          emptyTitle="No invoices found"
          emptyDescription="Submitted invoices from GLTS will appear here once finance shares them with your account."
        />
      }
      pagination={
        <CustomerListingPagination
          page={listing.tableState.page}
          pageSize={listing.tableState.pageSize}
          total={listing.total}
          onPage={page => listing.setTableState(s => ({ ...s, page }))}
          onPageSize={pageSize => listing.setTableState(s => ({ ...s, pageSize, page: 0 }))}
        />
      }
    />
  )
}
