import type { ReconciliationClaimSheetRow, ReconciliationStatus } from '@/shared/types/reconciliation'
import {
  CLAIM_SHEET_STATUS_LABEL,
  getClaimSheetFundTransferLabel,
  isClaimSheetBankTransferKpis,
} from '@/shared/types/groundOpsClaimSheet'
import { formatInr } from '@/shared/utils/invoiceCalculations'
import {
  formatSettlementAmountLabel,
} from '@/shared/utils/fundSettlementDisplay'
import { getReconciliationStatusLabel } from '../config/reconciliationListingConfig'

export function matchesReconciliationClaimSheetSearch(
  row: ReconciliationClaimSheetRow,
  query: string,
): boolean {
  const q = query.trim().toLowerCase()
  if (!q) return true

  const sheet = row.sheet
  return [
    sheet.claimNumber,
    sheet.generatedBy,
    sheet.team,
    sheet.status,
    CLAIM_SHEET_STATUS_LABEL[sheet.status],
    getClaimSheetFundTransferLabel(sheet.fundTransferType),
    sheet.fundTransferType,
    row.referenceNumber,
    row.reconciledBy,
    getReconciliationStatusLabel(row.status),
    ...sheet.cases.map(
      c => `${c.passengerName} ${c.operationalId} ${c.applicationId} ${c.companyName}`,
    ),
  ]
    .join(' ')
    .toLowerCase()
    .includes(q)
}

export function getReconciliationClaimSheetCellValue(
  row: ReconciliationClaimSheetRow,
  key: string,
): string {
  const sheet = row.sheet
  switch (key) {
    case 'claimNumber':
      return sheet.claimNumber
    case 'fundTransferType':
      return getClaimSheetFundTransferLabel(sheet.fundTransferType)
    case 'generatedBy':
      return sheet.generatedBy
    case 'team':
      return sheet.team || '—'
    case 'claimSheetStatus':
      return CLAIM_SHEET_STATUS_LABEL[sheet.status]
    case 'caseCount':
      return String(sheet.cases.length)
    case 'allocatedAmount':
      return formatInr(sheet.kpis.allocatedAmount)
    case 'expensesIncurred':
      return formatInr(sheet.kpis.expensesIncurred)
    case 'settlementAmount':
      return formatSettlementAmountLabel(
        sheet.kpis.settlementAmount,
        isClaimSheetBankTransferKpis(sheet.fundTransferType)
          ? 'closing_cash'
          : 'expense_vs_allocated',
      )
    case 'generatedAt':
      return sheet.generatedAt
    case 'reconciliationStatus':
      return getReconciliationStatusLabel(row.status)
    case 'reconciledBy':
      return row.reconciledBy || '—'
    default:
      return ''
  }
}

export function computeClaimSheetReconciliationKpis(rows: ReconciliationClaimSheetRow[]) {
  const pending = rows.filter(row => row.status === 'pending').length
  const submitted = rows.filter(row => row.status === 'submitted').length
  const rejected = rows.filter(row => row.status === 'rejected').length
  const totalAmount = rows.reduce((sum, row) => sum + row.sheet.kpis.settlementAmount, 0)
  return {
    total: rows.length,
    pending,
    submitted,
    rejected,
    totalAmount,
  }
}

export function getClaimSheetReconciliationEmptyState(
  hasSearch: boolean,
  statusTab: ReconciliationStatus = 'pending',
) {
  if (hasSearch) {
    return {
      title: 'No matching claim sheets',
      description: 'Try a different search or clear filters.',
    }
  }
  if (statusTab === 'submitted') {
    return {
      title: 'No submitted claim sheets in this period',
      description: 'Reconciled claim sheets will appear here after you submit them from Pending.',
    }
  }
  if (statusTab === 'rejected') {
    return {
      title: 'No rejected claim sheets in this period',
      description: 'Rejected claim sheets will appear here when you reject a pending item.',
    }
  }
  return {
    title: 'No pending claim sheets in this period',
    description:
      'Approved claim sheets from Fund Allocation will appear here for book-entry reconciliation.',
  }
}

export function downloadClaimSheetReconciliationCsv(rows: ReconciliationClaimSheetRow[]) {
  const headers = [
    'Claim Number',
    'Transfer Type',
    'Generated By',
    'Team',
    'Claim Sheet Status',
    'Cases',
    'Allocated Amount',
    'Expenses Incurred',
    'Settlement Amount',
    'Generated At',
    'Reconciliation Status',
    'User',
  ]

  const lines = rows.map(row => {
    const sheet = row.sheet
    const convention = isClaimSheetBankTransferKpis(sheet.fundTransferType)
      ? 'closing_cash'
      : 'expense_vs_allocated'
    return [
      sheet.claimNumber,
      getClaimSheetFundTransferLabel(sheet.fundTransferType),
      sheet.generatedBy,
      sheet.team,
      CLAIM_SHEET_STATUS_LABEL[sheet.status],
      sheet.cases.length,
      sheet.kpis.allocatedAmount,
      sheet.kpis.expensesIncurred,
      formatSettlementAmountLabel(sheet.kpis.settlementAmount, convention),
      sheet.generatedAt,
      getReconciliationStatusLabel(row.status),
      row.reconciledBy || '',
    ]
  })

  const escape = (value: string | number) => {
    const text = String(value ?? '')
    if (/[",\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`
    return text
  }

  const csv = [headers, ...lines].map(line => line.map(escape).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `reconciliation-claim-sheets-${new Date().toISOString().slice(0, 10)}.csv`
  link.click()
  URL.revokeObjectURL(url)
}

export function mapClaimSheetRowsToGridItems(rows: ReconciliationClaimSheetRow[]) {
  return rows.map(row => ({
    id: row.id,
    title: row.sheet.claimNumber,
    subtitle: `${row.sheet.generatedBy} · ${row.sheet.team || '—'}`,
    meta: `${row.sheet.cases.length} case${row.sheet.cases.length === 1 ? '' : 's'}`,
    status: getReconciliationStatusLabel(row.status),
    statusColor: (row.status === 'submitted'
      ? 'success'
      : row.status === 'rejected'
        ? 'default'
        : 'warning') as 'success' | 'warning' | 'default',
  }))
}
