import type { Column } from '@/design-system/UIComponents'
import { Button } from '@/design-system/UIComponents'
import { Grid } from '@mui/material'
import {
  DashboardTable,
  DASHBOARD_SPACING,
  ExpenseSummary,
  StatusBadge,
} from '../../shared'
import type { GroundClaimSheetRow, GroundOperationsDashboardTabProps } from '../types'

export function ClaimSheetsTab({
  data,
  loading,
  onRetry,
  onNavigate,
  onOpenClaimSheet,
}: GroundOperationsDashboardTabProps) {
  const columns: Column<GroundClaimSheetRow>[] = [
    { key: 'claimNumber', label: 'Claim', widthSize: 'md', sortable: false },
    { key: 'generatedBy', label: 'Generated by', widthSize: 'md', sortable: false },
    { key: 'team', label: 'Team', widthSize: 'sm', sortable: false },
    {
      key: 'status',
      label: 'Status',
      widthSize: 'sm',
      sortable: false,
      render: (_value, row) => <StatusBadge label={row.status} status={row.status} />,
    },
    { key: 'caseCount', label: 'Cases', widthSize: 'sm', sortable: false },
    { key: 'grandTotal', label: 'Total', widthSize: 'md', sortable: false },
    { key: 'generatedAt', label: 'Generated', widthSize: 'md', sortable: false },
    {
      key: 'actions',
      label: '',
      hideable: false,
      sortable: false,
      filterable: false,
      searchable: false,
      render: (_value, row) => (
        <Button
          label="Open"
          variant="text"
          size="sm"
          onClick={() => onOpenClaimSheet?.(row.id)}
        />
      ),
    },
  ]

  const rejected = data.claimSheetRows.filter(row => /rejected/i.test(row.status))

  return (
    <Grid container spacing={DASHBOARD_SPACING.field}>
      <Grid size={{ xs: 12 }}>
        <ExpenseSummary
          title="Claim sheet status"
          subtitle="Submitted for Finance review · approve / reject / resubmit"
          data={data.expenseSummary}
          loading={loading}
          onRetry={onRetry}
        />
      </Grid>
      <Grid size={{ xs: 12 }}>
        <DashboardTable
          title="Claim sheets"
          subtitle={
            rejected.length > 0
              ? `${rejected.length} rejected — open Operations Desk to edit and resubmit`
              : 'Ground Ops claims shared with Finance fund allocation'
          }
          columns={columns}
          data={data.claimSheetRows}
          rowKey="id"
          loading={loading}
          pageSize={8}
          onRowClick={row => onOpenClaimSheet?.(row.id)}
          onViewAll={() => onNavigate('/admin/ground-operations/case-handling')}
          actionLabel="Open desk"
          emptyTitle="No claim sheets"
          emptyDescription="Generate claim sheets from Operations Desk to track Finance review here."
        />
      </Grid>
    </Grid>
  )
}
