import { Stack } from '@mui/material'
import { Button, Drawer, useToast } from '@/design-system/UIComponents'
import { ClaimSheetDetailBody } from '@/pages/admin/ground-operations/case-handling/components/ClaimSheetDetailBody'
import { groundOpsClaimSheetService } from '@/shared/services/groundOpsClaimSheetService'
import type { GroundOpsClaimSheet } from '@/shared/types/groundOpsClaimSheet'

interface FundAllocationClaimSheetDetailDrawerProps {
  open: boolean
  sheet: GroundOpsClaimSheet | null
  onClose: () => void
}

export function FundAllocationClaimSheetDetailDrawer({
  open,
  sheet,
  onClose,
}: FundAllocationClaimSheetDetailDrawerProps) {
  const { showToast } = useToast()

  return (
    <Drawer
      open={open}
      onClose={onClose}
      title={sheet?.claimNumber ?? 'Claim sheet'}
      subtitle={sheet ? `Generated by ${sheet.generatedBy}` : undefined}
      width={640}
      bodyVariant="default"
      footer={
        <Stack direction="row" justifyContent="flex-end">
          <Button label="Close" variant="neutral" onClick={onClose} />
        </Stack>
      }
    >
      {sheet ? (
        <ClaimSheetDetailBody
          sheet={sheet}
          onDownloadPdf={() =>
            showToast({
              title: 'PDF download started',
              description: groundOpsClaimSheetService.getPdfDownloadLabel(sheet),
              variant: 'success',
            })
          }
          onDownloadProofs={() =>
            showToast({
              title: 'Proofs download started',
              description: groundOpsClaimSheetService.getProofsDownloadLabel(sheet),
              variant: 'success',
            })
          }
        />
      ) : null}
    </Drawer>
  )
}
