import { useState } from 'react'
import { Stack } from '@mui/material'
import { Button, ConfirmDialog, Drawer, useToast } from '@/design-system/UIComponents'
import { ClaimSheetDetailBody } from '@/pages/admin/ground-operations/case-handling/components/ClaimSheetDetailBody'
import { groundOpsClaimSheetService } from '@/shared/services/groundOpsClaimSheetService'
import type { GroundOpsClaimSheet } from '@/shared/types/groundOpsClaimSheet'
import { canFinanceReviewClaimSheet } from '@/shared/types/groundOpsClaimSheet'

interface FundAllocationClaimSheetDetailDrawerProps {
  open: boolean
  sheet: GroundOpsClaimSheet | null
  onClose: () => void
  onReviewed?: () => void
}

type ReviewConfirm = 'approve' | 'reject' | null

export function FundAllocationClaimSheetDetailDrawer({
  open,
  sheet,
  onClose,
  onReviewed,
}: FundAllocationClaimSheetDetailDrawerProps) {
  const { showToast } = useToast()
  const [confirmAction, setConfirmAction] = useState<ReviewConfirm>(null)

  const canReview = sheet ? canFinanceReviewClaimSheet(sheet.status) : false

  const handleClose = () => {
    setConfirmAction(null)
    onClose()
  }

  const handleConfirmReview = () => {
    if (!sheet || !confirmAction) return

    const result =
      confirmAction === 'approve'
        ? groundOpsClaimSheetService.approve(sheet.id)
        : groundOpsClaimSheetService.reject(sheet.id)

    if (!result.ok || !result.sheet) {
      showToast({
        title: confirmAction === 'approve' ? 'Could not approve' : 'Could not reject',
        description: result.error,
        variant: 'error',
      })
      setConfirmAction(null)
      return
    }

    showToast({
      title: confirmAction === 'approve' ? 'Claim sheet approved' : 'Claim sheet rejected',
      description:
        confirmAction === 'approve'
          ? `${result.sheet.claimNumber} is approved for settlement.`
          : `${result.sheet.claimNumber} was rejected.`,
      variant: confirmAction === 'approve' ? 'success' : 'warning',
    })
    setConfirmAction(null)
    onReviewed?.()
    onClose()
  }

  return (
    <>
      <Drawer
        open={open}
        onClose={handleClose}
        title={sheet?.claimNumber ?? 'Claim sheet'}
        subtitle={sheet ? `Generated by ${sheet.generatedBy}` : undefined}
        width={640}
        bodyVariant="default"
        footer={
          <Stack direction="row" justifyContent="space-between" spacing={1} width="100%">
            <Button label="Close" variant="neutral" onClick={handleClose} />
            {canReview ? (
              <Stack direction="row" spacing={1}>
                <Button
                  label="Reject"
                  variant="outlined"
                  color="error"
                  onClick={() => setConfirmAction('reject')}
                />
                <Button
                  label="Approve"
                  variant="contained"
                  onClick={() => setConfirmAction('approve')}
                />
              </Stack>
            ) : null}
          </Stack>
        }
      >
        {sheet ? (
          <ClaimSheetDetailBody
            sheet={sheet}
            onDownloadPdf={() =>
              showToast({
                title: 'PDF download started',
                description: groundOpsClaimSheetService.getPdfDownloadLabel(sheet),
                variant: 'success',
              })
            }
            onDownloadProofs={() =>
              showToast({
                title: 'Proofs download started',
                description: groundOpsClaimSheetService.getProofsDownloadLabel(sheet),
                variant: 'success',
              })
            }
          />
        ) : null}
      </Drawer>

      <ConfirmDialog
        open={confirmAction === 'approve'}
        onClose={() => setConfirmAction(null)}
        title="Approve claim sheet"
        description={
          sheet
            ? `Approve ${sheet.claimNumber}? Finance will mark this claim as approved.`
            : undefined
        }
        confirmLabel="Approve"
        onConfirm={handleConfirmReview}
      />

      <ConfirmDialog
        open={confirmAction === 'reject'}
        onClose={() => setConfirmAction(null)}
        title="Reject claim sheet"
        description={
          sheet
            ? `Reject ${sheet.claimNumber}? Ground Operations will need to revise and resubmit.`
            : undefined
        }
        confirmLabel="Reject"
        variant="destructive"
        onConfirm={handleConfirmReview}
      />
    </>
  )
}
