import { Typography } from '@mui/material'
import { Check, Eye, X } from 'lucide-react'
import { Badge, RowActions, type Column, type RowAction } from '@/design-system/UIComponents'
import { adminListingColumnWidthSize } from '@/pages/admin/components/listing'
import type { GroundOpsClaimSheet, GroundOpsClaimSheetStatus } from '@/shared/types/groundOpsClaimSheet'
import {
  canFinanceReviewClaimSheet,
  CLAIM_SHEET_STATUS_LABEL,
  getClaimSheetFundTransferLabel,
  isClaimSheetBankTransferKpis,
} from '@/shared/types/groundOpsClaimSheet'
import { formatDisplayDateTime } from '@/shared/utils/formatDisplayDate'
import { formatInr } from '@/shared/utils/invoiceCalculations'
import {
  formatSettlementAmountLabel,
  getSettlementAmountColor,
  getSettlementAmountTone,
} from '@/shared/utils/fundSettlementDisplay'

export type FundAllocationClaimSheetAction = 'view_details' | 'approve' | 'reject'

export interface FundAllocationClaimSheetTableColumnsParams {
  onAction: (action: FundAllocationClaimSheetAction, row: GroundOpsClaimSheet) => void
}

function formatGeneratedAt(value: string): string {
  return formatDisplayDateTime(value)
}

function AmountCell({
  value,
  emphasize = false,
  color,
}: {
  value: string
  emphasize?: boolean
  color?: string
}) {
  return (
    <Typography
      variant="body2"
      color={color}
      sx={{ fontSize: 13, fontWeight: emphasize ? 600 : 500 }}
      noWrap
    >
      {value}
    </Typography>
  )
}

function claimSheetStatusBadgeColor(
  status: GroundOpsClaimSheetStatus,
): 'info' | 'warning' | 'success' | 'error' | 'neutral' {
  switch (status) {
    case 'submitted':
      return 'info'
    case 'under_review':
      return 'warning'
    case 'approved':
      return 'success'
    case 'rejected':
      return 'error'
    case 'settled':
      return 'neutral'
    default:
      return 'neutral'
  }
}

export function buildFundAllocationClaimSheetTableColumns(
  params: FundAllocationClaimSheetTableColumnsParams,
): Column<GroundOpsClaimSheet>[] {
  return [
    {
      key: 'claimNumber',
      label: 'Claim number',
      widthSize: adminListingColumnWidthSize('name'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" fontWeight={600} noWrap sx={{ fontSize: 13 }}>
          {row.claimNumber}
        </Typography>
      ),
    },
    {
      key: 'fundTransferType',
      label: 'Transfer type',
      widthSize: adminListingColumnWidthSize('status'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {getClaimSheetFundTransferLabel(row.fundTransferType)}
        </Typography>
      ),
    },
    {
      key: 'generatedBy',
      label: 'Generated by',
      widthSize: adminListingColumnWidthSize('name'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {row.generatedBy || '—'}
        </Typography>
      ),
    },
    {
      key: 'team',
      label: 'Team',
      widthSize: adminListingColumnWidthSize('status'),
      sortable: true,
      searchable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {row.team || '—'}
        </Typography>
      ),
    },
    {
      key: 'status',
      label: 'Status',
      widthSize: 'md',
      sortable: true,
      render: (_value, row) => (
        <Badge
          label={CLAIM_SHEET_STATUS_LABEL[row.status]}
          color={claimSheetStatusBadgeColor(row.status)}
        />
      ),
    },
    {
      key: 'caseCount',
      label: 'Cases',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => (
        <Typography variant="body2" sx={{ fontSize: 13 }}>
          {row.cases.length}
        </Typography>
      ),
    },
    {
      key: 'allocatedAmount',
      label: 'Allocated amount',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => <AmountCell value={formatInr(row.kpis.allocatedAmount)} />,
    },
    {
      key: 'expensesIncurred',
      label: 'Expenses incurred',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => <AmountCell value={formatInr(row.kpis.expensesIncurred)} />,
    },
    {
      key: 'settlementAmount',
      label: 'Settlement amount',
      widthSize: adminListingColumnWidthSize('count'),
      sortable: true,
      render: (_value, row) => {
        const convention = isClaimSheetBankTransferKpis(row.fundTransferType)
          ? 'closing_cash'
          : 'expense_vs_allocated'
        return (
          <AmountCell
            value={formatSettlementAmountLabel(row.kpis.settlementAmount, convention)}
            color={getSettlementAmountColor(
              getSettlementAmountTone(row.kpis.settlementAmount, convention),
            )}
            emphasize
          />
        )
      },
    },
    {
      key: 'generatedAt',
      label: 'Generated at',
      widthSize: adminListingColumnWidthSize('date'),
      sortable: true,
      render: (_value, row) => (
        <Typography variant="body2" noWrap sx={{ fontSize: 13 }}>
          {formatGeneratedAt(row.generatedAt)}
        </Typography>
      ),
    },
    {
      key: 'actions',
      label: '',
      hideable: false,
      sortable: false,
      filterable: false,
      searchable: false,
      render: (_value, row) => {
        const actions: RowAction[] = [
          {
            label: 'View details',
            icon: <Eye size={16} />,
            onClick: () => params.onAction('view_details', row),
          },
        ]

        if (canFinanceReviewClaimSheet(row.status)) {
          actions.push(
            {
              label: 'Approve',
              icon: <Check size={16} />,
              onClick: () => params.onAction('approve', row),
            },
            {
              label: 'Reject',
              icon: <X size={16} />,
              onClick: () => params.onAction('reject', row),
              variant: 'destructive' as const,
            },
          )
        }

        return <RowActions row={row} actions={actions} />
      },
    },
  ]
}
