import { useState } from 'react'
import { Stack } from '@mui/material'
import { Button, ConfirmDialog, Drawer, useToast } from '@/design-system/UIComponents'
import { ClaimSheetDetailBody } from '@/pages/admin/ground-operations/case-handling/components/ClaimSheetDetailBody'
import { groundOpsClaimSheetService } from '@/shared/services/groundOpsClaimSheetService'
import type { GroundOpsClaimSheet } from '@/shared/types/groundOpsClaimSheet'
import { canFinanceReviewClaimSheet } from '@/shared/types/groundOpsClaimSheet'
import { FundAllocationClaimSheetRejectModal } from './FundAllocationClaimSheetRejectModal'

interface FundAllocationClaimSheetDetailDrawerProps {
  open: boolean
  sheet: GroundOpsClaimSheet | null
  onClose: () => void
  onReviewed?: () => void
}

export function FundAllocationClaimSheetDetailDrawer({
  open,
  sheet,
  onClose,
  onReviewed,
}: FundAllocationClaimSheetDetailDrawerProps) {
  const { showToast } = useToast()
  const [approveOpen, setApproveOpen] = useState(false)
  const [rejectOpen, setRejectOpen] = useState(false)

  const canReview = sheet ? canFinanceReviewClaimSheet(sheet.status) : false

  const handleClose = () => {
    setApproveOpen(false)
    setRejectOpen(false)
    onClose()
  }

  const handleApprove = () => {
    if (!sheet) return

    const result = groundOpsClaimSheetService.approve(sheet.id)
    if (!result.ok || !result.sheet) {
      showToast({
        title: 'Could not approve',
        description: result.error,
        variant: 'error',
      })
      setApproveOpen(false)
      return
    }

    showToast({
      title: 'Claim sheet approved',
      description: `${result.sheet.claimNumber} is approved for settlement.`,
      variant: 'success',
    })
    setApproveOpen(false)
    onReviewed?.()
    onClose()
  }

  const handleReject = (reason: string) => {
    if (!sheet) return

    const result = groundOpsClaimSheetService.reject(sheet.id, reason)
    if (!result.ok || !result.sheet) {
      showToast({
        title: 'Could not reject',
        description: result.error,
        variant: 'error',
      })
      return
    }

    showToast({
      title: 'Claim sheet rejected',
      description: `${result.sheet.claimNumber} was rejected. Ground Operations can revise and resubmit.`,
      variant: 'warning',
    })
    setRejectOpen(false)
    onReviewed?.()
    onClose()
  }

  return (
    <>
      <Drawer
        open={open}
        onClose={handleClose}
        title={sheet?.claimNumber ?? 'Claim sheet'}
        subtitle={sheet ? `Generated by ${sheet.generatedBy}` : undefined}
        width={640}
        bodyVariant="default"
        footer={
          <Stack direction="row" justifyContent="space-between" spacing={1} width="100%">
            <Button label="Close" variant="neutral" onClick={handleClose} />
            {canReview ? (
              <Stack direction="row" spacing={1}>
                <Button
                  label="Reject"
                  variant="outlined"
                  color="error"
                  onClick={() => setRejectOpen(true)}
                />
                <Button
                  label="Approve"
                  variant="contained"
                  onClick={() => setApproveOpen(true)}
                />
              </Stack>
            ) : null}
          </Stack>
        }
      >
        {sheet ? (
          <ClaimSheetDetailBody
            sheet={sheet}
            onDownloadPdf={() =>
              showToast({
                title: 'PDF download started',
                description: groundOpsClaimSheetService.getPdfDownloadLabel(sheet),
                variant: 'success',
              })
            }
            onDownloadProofs={() =>
              showToast({
                title: 'Proofs download started',
                description: groundOpsClaimSheetService.getProofsDownloadLabel(sheet),
                variant: 'success',
              })
            }
          />
        ) : null}
      </Drawer>

      <ConfirmDialog
        open={approveOpen}
        onClose={() => setApproveOpen(false)}
        title="Approve claim sheet"
        description={
          sheet
            ? `Approve ${sheet.claimNumber}? Finance will mark this claim as approved.`
            : undefined
        }
        confirmLabel="Approve"
        onConfirm={handleApprove}
      />

      <FundAllocationClaimSheetRejectModal
        open={rejectOpen}
        sheet={sheet}
        onClose={() => setRejectOpen(false)}
        onConfirm={handleReject}
      />
    </>
  )
}
