import type { ApplicationCustomerSegment } from '@/pages/customer/features/applications/types/applicationListing.types'

export const GLTS_MAR_1025_APPLICATION_ID = 'GLTS-MAR-1025' as const

export type ApplicationExpenseSource =
  | 'application_service'
  | 'ground_operations'
  | 'vendor_service'
  | 'ticket_related'
  | 'insurance_related'
  | 'manual_finance_entry'

export type ApplicationExpenseCreatedFrom =
  | 'application_service'
  | 'ground_operations'
  | 'vendor_service'
  | 'ticket_upload'
  | 'insurance_upload'
  | 'manual_finance_entry'

export type ApplicationExpenseServiceSource =
  | 'glts_service'
  | 'vendor_service'
  | 'vfs_service'
  | 'ground_staff_service'
  | 'embassy_consulate'
  | 'courier_partner'
  | 'insurance_vendor'
  | 'ticket_vendor'
  | 'other'

export type ApplicationExpensePassengerMappingScope =
  | 'application'
  | 'passenger'
  | 'multiple_passengers'
  | 'entire_crew'

export type ApplicationExpenseApprovalStatus =
  | 'draft'
  | 'pending_approval'
  | 'approved'
  | 'rejected'
  | 'clarification_required'

export type ApplicationExpensePaymentStatus =
  | 'not_paid'
  | 'paid'
  | 'partially_paid'
  | 'pending_reimbursement'

export type ApplicationExpenseProofStatus = 'not_required' | 'missing' | 'uploaded' | 'verified'

export type ApplicationExpensePaidBy = 'glts_team' | 'vendor' | 'customer' | 'ground_team'

export type ApplicationExpenseBillTo = 'client' | 'glts_cost' | 'vendor_adjustment'

export type ApplicationExpenseProofDocumentType =
  | 'bill'
  | 'receipt'
  | 'invoice'
  | 'supporting_document'

export type ApplicationExpenseType =
  | 'glts_service_fee'
  | 'visa_processing_fee'
  | 'documentation_service'
  | 'vfs_booking_service'
  | 'embassy_fee'
  | 'courier_service'
  | 'ground_operation_service'
  | 'vendor_service'
  | 'flight_ticket'
  | 'train_ticket'
  | 'bus_ticket'
  | 'marine_ticket'
  | 'insurance'
  | 'travel_insurance'
  | 'other'

export interface ApplicationExpensePassengerMapping {
  scope: ApplicationExpensePassengerMappingScope
  passengerIds?: string[]
  displayLabel: string
}

export interface ApplicationExpenseRecord {
  id: string
  expenseId: string
  applicationId: string
  expenseName: string
  expenseType: ApplicationExpenseType
  expenseTypeLabel: string
  expenseSource: ApplicationExpenseSource
  serviceSource: ApplicationExpenseServiceSource
  serviceSourceLabel: string
  linkedService?: string
  passengerMapping: ApplicationExpensePassengerMapping
  vendorStaffPartner?: string
  amount: number
  gstIncluded: boolean
  gstAmount: number
  tdsApplicable: boolean
  tdsAmount: number
  netPayableAmount: number
  paymentStatus: ApplicationExpensePaymentStatus
  approvalStatus: ApplicationExpenseApprovalStatus
  proofStatus: ApplicationExpenseProofStatus
  proofFileName?: string
  proofDocumentType?: ApplicationExpenseProofDocumentType
  paidBy?: ApplicationExpensePaidBy
  billTo?: ApplicationExpenseBillTo
  createdFrom: ApplicationExpenseCreatedFrom
  createdBy: string
  createdDate: string
  expenseDate?: string
  paymentMode?: string
  remarks?: string
  internalRemarks?: string
  rejectionReason?: string
  clarificationComment?: string
  readyForReconciliation?: boolean
  isAutoGenerated?: boolean
  vendorInvoiceNumber?: string
  vendorGstNumber?: string
  updatedAt: string
}

export type ApplicationExpenseRollupApprovalStatus =
  | 'none'
  | 'pending'
  | 'partial'
  | 'approved'
  | 'rejected'
  | 'clarification'

export type ApplicationExpenseRollupPaymentStatus =
  | 'none'
  | 'not_paid'
  | 'partially_paid'
  | 'paid'
  | 'pending_reimbursement'

export interface ApplicationExpenseListingRow {
  id: string
  applicationId: string
  companyName: string
  vesselName: string
  crewCount: number
  visaCountry: string
  visaType: string
  jurisdiction: string
  submissionDate: string
  totalExpense: number
  pendingExpense: number
  approvalStatus: ApplicationExpenseRollupApprovalStatus
  paymentStatus: ApplicationExpenseRollupPaymentStatus
  customerSegment: ApplicationCustomerSegment
  recordType: 'single' | 'bulk'
  assignedTeamId?: string
  assignedUserId?: string
  priority?: string
  travelDate: string
  applicationStatus: string
}

export interface ApplicationExpensePassengerSummaryRow {
  passengerId: string
  passengerName: string
  passportNumber: string
  cdcNumber: string
  rank: string
  status: string
  individualExpenseTotal: number
}

export interface ApplicationExpenseFinanceKpis {
  totalExpense: number
  autoAddedExpense: number
  manualExpense: number
  pendingApproval: number
  approvedExpense: number
  rejectedExpense: number
  paidAmount: number
  pendingPayment: number
}

export interface ApplicationExpenseDetailView {
  applicationId: string
  companyName: string
  vesselName: string
  crewCount: number
  visaCountry: string
  visaType: string
  jurisdiction: string
  submissionDate: string
  travelDate: string
  applicationStatus: string
  assignedTeam?: string
  assignedUser?: string
  priority?: string
  recordType: 'single' | 'bulk'
  customerSegment: ApplicationCustomerSegment
  passengers: ApplicationExpensePassengerSummaryRow[]
  financeKpis: ApplicationExpenseFinanceKpis
  expenses: ApplicationExpenseRecord[]
}

export interface ExpenseApprovalQueueRow {
  id: string
  expenseRecordId: string
  applicationId: string
  companyName: string
  expenseName: string
  serviceSourceLabel: string
  vendorStaffPartner: string
  passengerMappingLabel: string
  amount: number
  proofStatus: ApplicationExpenseProofStatus
  createdBy: string
  createdDate: string
  approvalStatus: ApplicationExpenseApprovalStatus
  customerSegment: ApplicationCustomerSegment
}

export interface ApplicationExpenseListingFilters {
  applicationId?: string
  company?: string
  vessel?: string
  visaCountry?: string
  jurisdiction?: string
  submissionDateFrom?: string
  submissionDateTo?: string
  approvalStatus?: ApplicationExpenseRollupApprovalStatus | ''
  paymentStatus?: ApplicationExpenseRollupPaymentStatus | ''
  query?: string
}

export interface UpsertApplicationExpenseInput {
  expenseName: string
  expenseType: ApplicationExpenseType
  expenseSource: ApplicationExpenseSource
  serviceSource: ApplicationExpenseServiceSource
  linkedService?: string
  passengerMapping: ApplicationExpensePassengerMapping
  vendorStaffPartner?: string
  expenseDate?: string
  amount: number
  gstIncluded: boolean
  gstAmount: number
  tdsApplicable: boolean
  tdsAmount: number
  netPayableAmount: number
  paymentMode?: string
  paymentStatus: ApplicationExpensePaymentStatus
  approvalStatus?: ApplicationExpenseApprovalStatus
  proofStatus?: ApplicationExpenseProofStatus
  proofFileName?: string
  proofDocumentType?: ApplicationExpenseProofDocumentType
  paidBy?: ApplicationExpensePaidBy
  billTo?: ApplicationExpenseBillTo
  internalRemarks?: string
}
